[package]
name = "Russel-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
urlencoding = "2.1.3"
reqwest = {version = "0.12.7",features = ["json"]}
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.100", features = [ "derive" ] }
serde_json ="1"
base64= "0.22"